name: "Setup Earthly"
description: "Download and setup Earthly in a GitHub Actions build environment"
author: "Bloomin' Labs"
inputs:
  version:
    description: "Version of the package to install, or 'latest' (default). This accepts semver ranges like ^3.0.0."
    required: true
    default: "latest"
  github-token:
    description: Token used to query earthly versions
    default: ${{ github.token }}
branding:
  icon: "terminal"
  color: "purple"
runs:
  using: "node16"
  main: "dist/index.js"
